### ISSUE TITLE
🐛 [Bug] Console errors when reloading on createPost route

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1373] opened 2019-08-23 12:56 UTC
## :bug: Bugreport
When I go to `localhost:3000/post/create` then reload the page I get a bunch of console errors:

<img width="651" alt="Screenshot 2019-08-23 at 13 48 49" src="https://user-images.githubusercontent.com/11694483/63593902-f2333600-c5ac-11e9-9993-f206684ec84f.png">

The page seems to work fine, though.

### Steps to reproduce the behavior
1. visit `localhost:3000/post/create`
2. open the console
3. reload the page

### Expected behavior
No console errors. 😛 

### Version & Environment
Type: [Desktop]
- OS: [macOS10.14.5]
- Browser: [Firefox]
- Version [68.0.2]
- Device: [MacbookPro]

### Additional context
I first thought it might have to do with the `Editor` component but I get the same errors when I remove it – so the problem must lie somewhere else.

**Comment by mattwr18** [comment] 2019-08-23 20:02
Duplicate of #1311

**Closed** 2019-08-23 21:39 UTC
Labels: bug
