### ISSUE TITLE
🐛 [Bug] Scrambled Placeholder when entering Comment Field

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1254] opened 2019-08-13 08:40 UTC
## :bug: Bugreport

When i want to write a comment the placeholder in the comment field gets scrambled, as soon as the comment field gets the focus.

![error-when-commenting](https://user-images.githubusercontent.com/13457963/62927152-402e8980-bdb6-11e9-8bab-9b0f3a0cc835.png)

### Steps to reproduce the behavior
1. Read an article
2. Enter the comment field

### Expected behavior

The placeholder should disappear when entering the comment field or when entering the first character.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [68.0.1]  
 - Device: [Notebook]

**Comment by roschaefer** [comment] 2019-08-13 08:59
duplicate of #1197 - I copy+pasted your texts, so it should be fixed on both comment and post.

**Closed by roschaefer** 2019-08-13 08:59 UTC
Labels: bug
