### ISSUE TITLE
[Epic] Badges System

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#319] opened 2019-03-27 08:56 UTC
```gherkin
Feature: Badges System
  As the network operator
  I want to grant badges to people for donations and other supportive accomplishments 
  In order to motivate these and show their support in the public, if they like.
```

**Comment by roschaefer** [comment] 2019-03-27 20:18
duplicate of #277

**Comment by ulfgebhardt** [comment] 2019-04-20 15:12
dependent issues have to be moved first!

**Closed** 2019-04-20 15:25 UTC
Labels: Epic
