### ISSUE TITLE
[Epic] CanDos

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#309] opened 2019-03-27 08:08 UTC
```gherkin
Feature: CanDos
  As a user
  I want to find interesting ideas and things to do
  In order to not just read, but come into action and make the world a better place.
```

**Comment by roschaefer** [comment] 2019-03-27 19:45
@datenbrei this is a great user-story but I believe this is a duplicate of #262

**Closed** 2019-04-20 15:36 UTC
