### ISSUE TITLE
[Feature] Chat

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#321] opened 2019-03-27 10:54 UTC
```gherkin
Feature: Chat
  As a user
  I want chat with other users 1:1 or maybe in chat groups
  In order to talk to people more directly and also to share personal information not visible to the public.
```

**Comment by mattwr18** [comment] 2019-11-20 15:22
@datenbrei is this somehow different from https://github.com/Human-Connection/Human-Connection/issues/38
I know this was created first, but there is more conversation about the issue and its implementation there, so can we close this?

**Comment by volanar** [comment] 2020-01-17 18:33
I suggest to make integration with Rocket chat. It is free, there is live chat, you can communicate with personal messages and there are group chats

**Comment by mattwr18** [comment] 2020-02-25 12:54
this is a duplicate of https://github.com/Human-Connection/Human-Connection/issues/38

**Closed by mattwr18** 2020-02-25 12:54 UTC
