### ISSUE TITLE
🐛 [Bug] Post Ribbons Are Not On The Right Height

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3426] opened 2020-04-06 08:34 UTC
## :bug: Bugreport

Post ribbons are not on the right height on the post cards in the news feed.

<img width="1769" alt="Bildschirmfoto 2020-04-06 um 10 19 34" src="https://user-images.githubusercontent.com/25344101/78538721-bbcfc180-77f1-11ea-82cc-ac3c426316a6.png">

### Steps to reproduce the behavior
1. log in
2. go to the newsfeed page
3. see the bug

### Expected behavior

Ribbons on post cards should be on the height of the user teaser right underneath the teaser image.

### Version & Environment
 Type: [Desktop]      
 - OS: [macOS]      
 - Browser: [Safari] 
 - Version []  
 - Device: []  

### Additional context

Good first inssue if you are familiar with CSS.

**Comment by alina-beck** [comment] 2020-04-06 09:02
duplicate of #3157

**Closed by alina-beck** 2020-04-06 09:02 UTC
Labels: bug, good first issue
