### ISSUE TITLE
🚀 [Feature] Post Visibility Draft

### ISSUE THREAD

**Issue by Raimundo-dev** [Human-Connection/Human-Connection#3461] opened 2020-04-09 14:34 UTC
### User Story
```gherkin
Feature: Post Visibility Draft
  As a user
  I want to save drafts of posts which are not visible for other users.
  In order to finish them later.
```

### User Problem

EN:
- I have an unfinished post and would like it not to be published when I save it.
- I want to make an already published post invisible so that I can republish it later.

DE:
- Ich habe einen unfertigen Post und möchte, dass er noch nicht publiziert wird, wenn ich ihn abspeichere.
- Ich möchte einen bereits publizierten Post unsichtbar machen, um ihn später verändert erneut zu publizieren.

### Implementation

EN:
It should be a menu on the post: registered users | draft (more future possibilities: #2198  #3252)
DE:
Es sollte ein Menü im Beitrag geben: Registrierte Benutzer | Entwurf (weitere zukünftige Möglichkeiten: #2198  #3252)

### Design & Layout

None

### Validation

None

### Additional context

- @roschaefer startet a PR on this #3169 .
- A related issue is as well #288 .

**Comment by Mogge** [comment] 2020-04-15 14:55
I like this idea. May be it could be linked to #288 ?

**Comment by Tirokk** [comment] 2020-04-22 13:17
Yeah @Mogge this is clearly linked to each other.
Thanks for the hint!

**Comment by sushidave** [comment] 2020-05-28 13:24
@Tirokk You asked me to review this issue. Here are my findings:

This feature request is a subset of #2198 and a duplicate of #3252 which:
- includes an auto-save function
- suggests to show the drafts to the user on his/her profile page

Should we use this issue or close it and use #3252 instead?

**Comment by Tirokk** [comment] 2020-05-29 09:32
I would say merge the informations of this one in to your issue #3252 . @sushidave 

This is a subset of #2198. Maybe #2198 can become an epic with checkboxes?
And auto-save can get a part with a checkbox of #3252 ?

- The auto-save solution of @rbeer was in the local storage of the browser. I don’t if he has time to develop on this for now.
- An auto-save solution in the database would be possible as well in my eyes.
- We do it KISS for now and just implement it simple at first.

**Comment by sushidave** [comment] 2020-05-29 15:33
@Tirokk Done. Closing this isssue.

**Closed by sushidave** 2020-05-29 15:33 UTC
Labels: feature
