### ISSUE TITLE
🚀 [Feature] Notifications – Additional Functions, Options and Settings

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#491] opened 2019-04-20 09:54 UTC
# :rocket: Functionality Suggestion

## User Story

My actual user experience in the old Alpha: An overload of notifications means an overload of work to review them …
If I was not in there for some days or haven’t worked on them.
Because I followed some users which posts a lot, as an example.

```gherkin
Feature: Sort notifications and/or display settings
  As a user
  I want to see first, if somebody has mentioned me personally.
  And later I can have a look what others posted.
```

```gherkin
Feature: Quick and save deletion of notifications
  As a user
  I want to be able to choose or search specific notifications.
  And view or delete them quickly (together) to reduce work overload.
```

**Comment by ulfgebhardt** [comment] 2019-04-20 10:58
Duplicate of https://github.com/Human-Connection/Human-Connection/issues/488

**Comment by Tirokk** [comment] 2019-04-20 11:22
Ups, sorry @ulfgebhardt . I have not recognised that you have moved my comment from the Notification Epic already to a new issue …

**Closed** 2019-04-20 11:23 UTC
Labels: Feature, discussion
